### ISSUE TITLE
Rubotyチームの写真について

### ISSUE THREAD

**Issue by corselia** [speee/code-party#53]
Rubotyチームで一枚だけ途中で写真を撮りましたので、よろしければご参照、ご利用ください。
- [Rubotyチームの風景](https://github.com/corselia/code-party/blob/rubykaigi-2018-feedback/feedback/ruboty_team.jpg)

ちなみに状況について説明しますと、gemが出来上がったので、実行して正しく返答が返ってくる瞬間を記念に撮ったところになります。返答は返って来なかったのですが……。

**Comment by kou** [comment]
あざっす！
pull requestにしてもらえますか！？
